spring:
  datasource:
    #로컬 DB(각자에 맞게 변경)
    url: jdbc:mysql://localhost:3306/FavoritePlace
    username: dongnae
    password: df1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000